// src/media/infrastructure/errors/storage-error-sub-category.enum.ts
export enum StorageErrorSubCategory {
  NOT_FOUND = 'NOT_FOUND',
  DUPLICATE = 'DUPLICATE',
  VALIDATION = 'VALIDATION',
  CONNECTION = 'CONNECTION',
  TIMEOUT = 'TIMEOUT',
  PERMISSION = 'PERMISSION',
  SIZE_LIMIT = 'SIZE_LIMIT',
  FORMAT_NOT_SUPPORTED = 'FORMAT_NOT_SUPPORTED',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
