export const SUBMIT_ANSWER_ERROR_CODES = {
  ATTEMPT_NOT_FOUND: 'ATTEMPT_NOT_FOUND',
  UNAUTHORIZED_ATTEMPT_ACCESS: 'UNAUTHORIZED_ATTEMPT_ACCESS',
  ATTEMPT_NOT_IN_PROGRESS: 'ATTEMPT_NOT_IN_PROGRESS',
  KAHOOT_NOT_FOUND: 'KAHOOT_NOT_FOUND',
  SLIDE_ALREADY_ANSWERED: 'SLIDE_ALREADY_ANSWERED',
  INVALID_SUBMISSION: 'INVALID_SUBMISSION',
  NO_NEXT_SLIDE: 'NO_NEXT_SLIDE',
} as const;