export const REGISTER_USER_ERROR_CODES = {
    USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
    USER_USERNAME_ALREADY_EXISTS: 'USER_USERNAME_ALREADY_EXISTS',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
  };