# Usamos la misma base que producción para mantener paridad
FROM node:20-slim

# Instalamos dependencias necesarias para algunas librerías de Node
RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# Copiamos archivos de configuración de dependencias
COPY package.json yarn.lock ./

# Instalamos TODAS las dependencias (incluyendo devDependencies)
RUN yarn install

# No copiamos el código aquí con 'COPY . .', porque en desarrollo 
# lo montaremos mediante VOLÚMENES en el docker-compose.
# Esto es lo que permite el Hot-Reload.

# Exponemos los puertos de la API y WebSockets
EXPOSE 3000
EXPOSE 3003

# Comando para iniciar en modo desarrollo
CMD ["yarn", "run", start:dev"]