// src/media/application/dependency-tokens/application-media.tokens.ts

export const MEDIA_TOKENS = {
  // Infrastructure
  ASSET_STORAGE_SERVICE: Symbol('ASSET_STORAGE_SERVICE'),
  ASSET_URL_GENERATOR: Symbol('ASSET_URL_GENERATOR'),
  CLOUDINARY_CONFIG: Symbol('CLOUDINARY_CONFIG'),

  // Services & Ports
  IMAGE_URL_ENRICHER: Symbol('IMAGE_URL_ENRICHER'),
  THEME_ENRICHER: Symbol('THEME_ENRICHER'),
  ENRICHMENT_HANDLER_FACTORY: Symbol('ENRICHMENT_HANDLER_FACTORY'),

  // Handlers & Config
  URL_ENRICHMENT_HANDLER: Symbol('URL_ENRICHMENT_HANDLER'),
  THEME_ENRICHMENT_HANDLER: Symbol('THEME_ENRICHER_HANDLER'),
  URL_CONFIGURABLE: Symbol('URL_CONFIGURABLE'),
} as const;