export const CHANGE_USERNAME_ERRORS = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
    USERNAME_CHANGE_COOLDOWN: 'USERNAME_CHANGE_COOLDOWN',
} as const;